### PR TITLE
feat: add flags to ignore files/directories

### PR DESCRIPTION
**Pull request by 1bitphoenix**
Add '--ignore-dir' flag to not include directories and '--ignore' flag
to not include files while asar packaging

Signed-off-by: Rituka Patwal <ritukapatwal21@gmail.com>

### CODE REVIEW

**Comment by 1bitphoenix** [comment]
@erickzhao @malept 
If anyone could review this PR? Not sure who should I tag here.

**Review by ckerr — DISMISSED** [review]
The idea and code both look fine, thank you for this patch!

However it doesn't look like you added anything to test/ to exercise these code paths. Would it be possible to add some tests for this feature?

**Comment by malept** [comment]
Generally speaking, instead of adding a new pair of options, I'd prefer to have `unpack` and `unpackDir` be enhanced to take an array of globs in addition to a single glob. The `glob` module should be able to specify ignores (just like the `files` array in `package.json`).

**Comment by 1bitphoenix** [comment]
H @ckerr,
I have update the PR by adding some tests. PTAL.

(PS: Sorry for the delay.)

**Comment by 1bitphoenix** [comment]
> The idea and code both look fine, thank you for this patch!
> 
> However it doesn't look like you added anything to test/ to exercise these code paths. Would it be possible to add some tests for this feature?

Hi @ckerr,
I have update the PR by adding some tests. PTAL.

(PS: Sorry for the delay.)

**Comment by 1bitphoenix** [comment]
> Generally speaking, instead of adding a new pair of options, I'd prefer to have `unpack` and `unpackDir` be enhanced to take an array of globs in addition to a single glob. The `glob` module should be able to specify ignores (just like the `files` array in `package.json`).

@malept 
I'm a little lost on how can we figure out from the list of globs which glob user wishes to unpack and which glob user wishes to ignore. Can you please explain your thoughts in detail?

**Comment by 1bitphoenix** [comment]
@ckerr 
Just a friendly ping. Can you review the PR with tests added?

**Pull request closed without merging**
