### PR TITLE
Add snapcraft.yaml

### PR DESCRIPTION
**Pull request by flexiondotorg**
This pull request adds a `snapcraft.yaml` that will allow `asar` to be hooked up to the [free GitHub integrated Snapcraft build service](https://build.snapcraft.io).

When this pull request is merged visit https://build.snapcraft.io and connect this asar repository. When that is complete builds of `asar` will be created for multiple architectures an published in the edge channel of the snap store so that millions of Linux users and developers are able to easily install `asar` via `snap install asar`.

### CODE REVIEW

**Comment by zcbenz** [comment]
@flexiondotorg I received this error on the snap craft site:

> (NEEDS REVIEW) confinement 'classic' not allowed. If your snap needs classic confinement to function, please make a request for this snap to use classic by creating a new topic in the forum using the 'store' category and detail the technical reasons why classic is required. lint-snap-v2_confinement_classic 

What's the best way to solve it?

**Comment by flexiondotorg** [comment]
So `asar` could potentially need to access any arbitrary file on the file system. Therefore I used classic confinement, which requires manual security review, to enable that. `asar` will be reviewed in due course and published. This review is only required once, not for subsequent builds.

**Comment by zcbenz** [comment]
Submitted a request at https://bugs.launchpad.net/snapstore/+bug/1730153.

**Comment by zcbenz** [comment]
@flexiondotorg Can you explain to the maintainers of snapcraft why classic confinement is needed at https://forum.snapcraft.io/t/allow-classic-confinement-for-electron-asar/2827?

**Comment by flexiondotorg** [comment]
Done :-)

**Pull request merged**
