### PR TITLE
feat: Extract All Async, Extract File Async

### PR DESCRIPTION
**Pull request by waseemshahwan**
New to open source contributions. All criticism is welcome.

I've had this problem myself when using with an electron process; the window shows as non-responding when extracting which I would have liked to fix. I also found that someone had this problem in issue #167  and it's been open for a while.

### CODE REVIEW

**Comment by malept** [comment]
How does this solution address https://github.com/electron/asar/issues/167#issuecomment-467595078 ?

**Comment by waseemshahwan** [comment]
> How does this solution address [#167 (comment)](https://github.com/electron/asar/issues/167#issuecomment-467595078) ?

Not sure what is meant in that comment. I just substituted all filesystem operation functions to use their async counterparts (fs.readFile vs fs.readFileSync). This does not block the event loop and therefore can be wrapped in a promise and run asynchronously. 

After some tests, this method worked. The process was no longer being blocked by these operations and the output was as expected.

**Comment by malept** [comment]
I believe it means that there's an inherent flaw in the file format where in certain cases, it's not safe to be asynchronously read the archive, especially with `extractAll`.

**Comment by waseemshahwan** [comment]
> I believe it means that there's an inherent flaw in the file format where in certain cases, it's not safe to be asynchronously read the archive, especially with extractAll.

Unless there is a fundamental difference between the native fs sync and non-sync functions, I can't imagine that to be the case. If the original commentator @MarshallOfSound can produce this potential flaw, I can look into possible fixes.

The fs.read and fs.readSync should always have the same behavior, and if they don't, then that is a flaw in the native package itself.

**Comment by ibrahimelement** [comment]
Waiting for this to be approved, desperately needed right now... Our team has been tracking down a bug related to this issue... Thanks waseem!

**Comment by Slapbox** [comment]
Any update on this? Looks promising.

**Comment by Slapbox** [comment]
@waseemshahwan why closed? I think this would be a great addition!

**Comment by waseemshahwan** [comment]
If authors of the repo are interested in merging I can reopen.

**Comment by Slapbox** [comment]
@zcbenz @MarshallOfSound

**Pull request closed without merging**
