### PR TITLE
build(deps): upgrade minimatch to ^3.0.5

### PR DESCRIPTION
**Pull request by Bharat-dev**
Upgrade minimatch to ^3.0.5 to address security vulnerabilities

### CODE REVIEW

**Comment by IoneMurray1** [comment]
Hello. Is there any reason this is not being approved by code owners?

**Comment by erickzhao** [comment]
Dunno if this is strictly necessary because the lockfile already specifies `3.1.2` for the `minimatch@^3.0.4` dependency.

https://github.com/electron/asar/blob/main/yarn.lock#L2698

**Comment by erikian** [comment]
It might be necessary because we don't publish the lockfile to npm, only the `package.json`, so if a project already has `minimatch@3.0.4` installed, `asar` will be happy with that version.

**Comment by MarshallOfSound** [comment]
This definitely isn't necessary, projects downstream can bump this dependency without us releasing entire new packages

**Pull request closed without merging**
