### PR TITLE
UnpackDir=xyz/{123,abc} pattern didn't match UnpackDir=xyz/123 and UnpackDir=xyz/abc combined

### PR DESCRIPTION
**Pull request by MathijsvVelde**
UnpackDir=xyz/{123,abc} pattern now matches UnpackDir=xyz/123 and UnpackDir=xyz/abc combined

### CODE REVIEW

**Comment by MathijsvVelde** [comment]
Rev: https://github.com/electron-userland/electron-packager/pull/336

**Comment by zcbenz** [comment]
I don't quite understand what "UnpackDir=xyz/123 and UnpackDir=xyz/abc combined" means, if it is not matching some files, we should file a bug at [minimatch](https://github.com/isaacs/minimatch).

**Comment by MathijsvVelde** [comment]
in the old code `isUnpackDir` results:

parameter `pattern` = `xyz/123`

| Path | path.indexOf(pattern) is 0 | minimatch path, pattern | returns `True` | 
|-------:|:----------------------------------:|:-------------------------------:|:-------------------:|
| xyz | false | false | false |
| xyz/123 | **`TRUE`** | true | true |
| xyz/123/sub | **`TRUE`** | **`FALSE`** | **`TRUE`** |
| xyz/123/sub/sub | **`TRUE`** | **`FALSE`** | **`TRUE`** |
| xyz | false | false | false |
| xyz/abc | false | false | false |
| xyz/abc/sub | false | false | false |
| xyz/abc/sub/sub | false | false | false |

parameter `pattern` = `xyz/{123,abc}`

| Path | path.indexOf(pattern) is 0 | minimatch path, pattern | returns `True` | 
|-------:|:----------------------------------:|:-------------------------------:|:-------------------:|
| xyz | false | false | false |
| xyz/123 | **`FALSE`** | **`TRUE`** | true |
| xyz/123/sub | **`FALSE`** | **`FALSE`** | **`FALSE`** |
| xyz/123/sub/sub | **`FALSE`** | **`FALSE`** | **`FALSE`** |
| xyz | false | false | false |
| xyz/abc | **`FALSE`** | **`TRUE`** | true |
| xyz/abc/sub | **`FALSE`** | **`FALSE`** | false |
| xyz/abc/sub/sub | **`FALSE`** | **`FALSE`** | false |

So when you use a path pattern like this:
- `xyz/{123,abc}` -> matches only the directories `xyz/123` and `xyz/abc` **themselves** and **not** it's content
- `xyz/{123,abc}/*` -> matches only the directories `xyz/123` and `xyz/abc` themselves and it's content except the subdirectories
- `xyz/{123,abc}/**` -> matches only the directories `xyz/123` and `xyz/abc` themselves and it's subdirectories except folders with a dot (like `.git`, `.htaccess`) and the files of `xyz/123` and `xyz/abc`
- `xyz/{123,abc}/**/*` -> matches only the directories `xyz/123` and `xyz/abc` themselves, it's subdirectories and the files of `xyz/123` and `xyz/abc`, except folders with a dot (like `.git`, `.htaccess`)

The same as in a Bash terminal.

The problem lies with `path.indexOf (Pattern)`, because `("xyz/123").indexOf("xyz/{123,abc}") is 0` will never be true due to the curly brackets and the commas.

path.indexOf table

| Path | Pattern | `is 0` |
|:-:|:-:|:-:|
| xyz/123 | xyz/123 | **YES** |
| xyz/123/sub/sub | xyz/123 | **YES** |
| xyz/abc | xyz/123 | **NO** |
| xyz/abc/sub/sub | xyz/123 | **NO** |
|---|---|---|
| xyz/123 | xyz/{123,abc} | **NO** |
| xyz/123/sub/sub | xyz/{123,abc} | **NO** |
| xyz/abc | xyz/{123,abc} | **NO** |
| xyz/abc/sub/sub | xyz/{123,abc} | **NO** |

It's a bit like `"xyz/123/sub/sub".match("xyz/123")` matches and `"xyz/123/sub/sub".match("xyz/{123,abc}")` not

Are you getting it?
At first I was also looking at minimatch, but compared to the terminal it works fine...

I hope I have made it clearer for you.

**Comment by MathijsvVelde** [comment]
@zcbenz, did you have the opportunity to look at this again? thanks!

**Comment by kevinsawicki** [comment]
@MathijsvVelde would it be possible for you to add some new tests around this changed behavior?

**Comment by MarshallOfSound** [comment]
@kevinsawicki I know this PR is ancient but can this be looked at again (I can adopt it if need be).

**Comment by kevinsawicki** [comment]
@MarshallOfSound thanks for bumping it, will take a look 🔍

**Comment by kevinsawicki** [comment]
Fixed in #99

**Pull request closed without merging**
